/*************************************************************************
 * Version        Date           Name               Description
 * =====================================================================
 * V1.0         14-02-2022      Developer2           Add Method implemented
 * 
 ************************************************************************/
public with sharing class Calculator {
    public Calculator() {
    }
    public Integer sub(integer a, integer b) {
        return a-b;
    }    
}